question_repo/apps/accounts/urls.py
from django.conf.urls import url,include

from . import views
urlpatterns = [
    url(r'register/$',views.Register.as_view(),name='register'),
    url(r'login/$',views.Login.as_view(),name='login'),
    url(r'logout/$',views.logout,name='logout'),
    url(r'password/forget/$',views.PasswordForget.as_view(),name='passwd_forget'),
    url(r'password/reset/(?P<verify_code>\w+)/$',views.PasswordReset.as_view(),name='passwd_reset'),
]

question_repo/apps/apis/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^mobile_captcha/$',views.get_mobile_captcha,name='mobile_captcha'),
    url(r'^get_captcha/$',views.get_captcha,name='get_captcha'),
    url(r'^check_captcha/$',views.check_captcha,name='check_captcha'),
    url(r'^questions/$',views.QuestionsView.as_view(),name='questions'),
    url(r'^question/collection/(?P<id>\d+)/$',views.QuestionCollectionView.as_view(),name='question_collection'),
    url(r'^answer/(?P<id>\d+)/$',views.AnswerView.as_view(),name='answer'),
    url(r'^other_answer/(?P<id>\d+)/$',views.OtherAnswerView.as_view(),name='other_answer'),
    url(r'^answer/collection/(?P<id>\d+)/$',views.AnswerCollectionView.as_view(),name='answer_collection'),
    url(r'^change_avator/$',views.ChangeAvator.as_view(),name='change_avator')
]

question_repo/apps/repo/urls.py
from django.conf.urls import url,include
from django.views.generic import TemplateView
from . import views
urlpatterns = [
    url('^$',views.index,name='index'),
    # 题目列表
    url('^questions/$',views.QuestionsList.as_view(),name='questions'),
    # 贡献题目
    url('^question/$',views.Question.as_view(),name='question'),
    # 题目详情
    url('^question/(?P<id>\d+)/$',views.QuestionDetail.as_view(),name='question_detail'),
]

question_repo/apps/usercenter/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    # 个人资料
    url(r'profile/$',views.ProfileView.as_view(),name='profile'),
    # 修改密码
    url(r'^change_passwd/$',views.ChangePasswdView.as_view(),name='change_passwd'),
    # 我的回答
    url(r'^answer/$',views.AnswerView.as_view(),name='answer'),
    # 我的收藏
    url(r'^collect/$',views.CollectView.as_view(),name='collect'),
    # 我的贡献
    url(r'^contribut/$',views.test,name='contribut'),
    # 待审题目
    url(r'^approval/$',views.ApprovalView.as_view(),name='approval'),
    # 审核题目
    url(r'^approval/(?P<id>\d+)/$',views.ApprovalPassView.as_view(),name='approval_pass'),

]

question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app01 import views
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'logtest/$', views.logtest,name='logtest'),
    # url(r'index/$',views.index,name='index'),
    url(r'accounts/',include('apps.accounts.urls',namespace='accounts')),
    url(r'apis/',include('apps.apis.urls',namespace='apis')),
    url(r'uc/',include('apps.usercenter.urls',namespace='uc')),
    url(r'^',include('apps.repo.urls',namespace='repo')),
    url(r'^paginator/$',views.Pagi.as_view()),

    # meida 处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # ckeditor
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
]

question_repo/templates/crontribute_modal.html
{# My Modal 模态框 #}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="myModal-1" class="modal fade">
<div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
          <h4 class="modal-title">贡献题目</h4>
      </div>
      <div class="modal-body">
          <form class="form-horizontal" role="form" method="post" action="/question/">
              <div class="form-group">
                  <label for="inputQuestionTitle" class="col-lg-2 control-label">标题</label>
                  <div class="col-lg-10">
                      <input type="text" class="form-control" id="inputQuestionTitle" name="title" placeholder="标题">
                  </div>
              </div>
               <div class="form-group">
                    {% csrf_token %}
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">分类</label>
                    <div class="col-lg-10">
                        <select class="form-control" id="分类" name="category">
                            <option value="0"> 选择分类 </option>
                            {% for item in category %}
                                <option value="{{ item.id }}">{{ item.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputQuestionTitle" class="col-lg-2 control-label">内容</label>
                    <div class="col-lg-10">
                        <textarea type="text" class="form-control" id="inputQuestionTitle" name="content" placeholder="内容"></textarea>
                    </div>
                </div>
              <div class="form-group">
                  <div class="col-lg-offset-2 col-lg-10">
                      <button type="submit" class="btn btn-default">提交</button>
                  </div>
              </div>
          </form>
      </div>
  </div>
</div>
</div>

question_repo/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}

{% block title %}首页{% endblock %}

{% block content %}
<aside class="profile-info col-lg-9">
    <!--features carousel start-->
    <section class="panel">
          <div class="flat-carousal">
              <div id="owl-demo" class="owl-carousel owl-theme" style="opacity: 1; display: block;">
                  <div class="owl-wrapper-outer">
                      <div class="owl-wrapper" style="width: 4926px; left: 0px; display: block;">
                          <div class="owl-item active" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告1</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告2</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                          <div class="owl-item" style="width: 821px;">
                              <div class="item">
                                  <h1>通知广告3</h1>
                                  <div class="text-center">
                                      <a href="javascript:;" class="view-all">View All</a>
                                  </div>
                              </div>
                          </div>
                      </div>
                  </div>

                  <div class="owl-controls clickable">
                      <div class="owl-pagination">
                          <div class="owl-page active"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                          <div class="owl-page"><span class=""></span></div>
                      </div>
                      <div class="owl-buttons">
                          <div class="owl-prev">prev</div>
                          <div class="owl-next">next</div>
                      </div>
                  </div>
              </div>
          </div>
    </section>
    <!--features carousel end-->

    <section class="panel">
          <header class="panel-heading">
              最新动态
          </header>
          <div class="panel-body">
              <div class="timeline-messages">
                  <!-- Comment -->
                  {% for item in userlog %}
                  <div class="msg-time-chat">
{#                      <a href="#" class="message-img"><img class="avatar" src="{{ item.user.avator_sor.url }}" alt="图片不存在"></a>#}
                      <a href="#" class="message-img"><img class="avatar" src="{{ item.user.avator_sor|thumbnail_url:'avatar' }}" alt="图片不存在"></a>
                      <div class="message-body {% if forloop.counter|divisibleby:2 %}msg-out{% else %}msg-in{% endif %}">
                          <span class="arrow"></span>
                          <div class="text">
                              <p class="attribution"><a href="#">{{ item.user }}</a>{{ item.create_time }}</p>
                              {% if item.operate == '3' %}
                                  <p>回答了<a href="{% url 'repo:question_detail' item.question_id %}">{{ item.question }}</a></p>
                              {% elif item.operate == '1' %}
                                  <p>收藏了<a href="{% url 'repo:question_detail' item.answer.question_id %}">{{ item.answer.question }}{{ item.answer.user }}的回答{{ item.answer.answer }}</a></p>
                              {% else %}
                                  <p>取消收藏了<a href="{% url 'repo:question_detail' item.answer.question_id %}">{{ item.answer.question }}{{ item.answer.user }}的回答{{ item.answer.answer }}</a></p>
                              {% endif %}

                          </div>
                      </div>
                  </div>
                  {% endfor %}
              </div>
          </div>
    </section>

    <!--最近刷题的同学 start-->
    <section class="panel">
        <header class="panel-heading">
          最近刷题的同学
        </header>
        <div class="panel-body">
            {% for item in users %}
             <div class="task-thumb">
                 <img src="{{ item.avator_sor|thumbnail_url:'avatar' }}" alt="">
                 <div class="clearfix"></div>
                 <a href="#">{{ item.username }}</a>
            </div>
            {% endfor %}
        </div>
    </section>
    <!--custom chart end-->
</aside>
<aside class="profile-info col-lg-3">
  <!--follower start-->
  <section class="panel">
      <div class="follower">
          <div class="panel-body">
              <div class="follow-ava">
{#                  <img src="{{ user.avator_sor.url }}" alt="">#}
                    <img src="{{ user.avator_sor|thumbnail_url:'avatar' }}" alt="" />
              </div>
              <h4>{{ user.username }}</h4>
              <h4>您已完成{{ user_data.answer_num }}道面试题，加油！</h4>
          </div>
      </div>
      <footer class="follower-foot">
          <ul>
              <li>
                  <h4>{{ user_data.answer_num }}/{{ user_data.question_all }}</h4>
                  <p>刷题量：{% widthratio user_data.answer_num user_data.question_all 100 %}%</p>
              </li>
              <li>
                  <h4>第{{ user_data.rank.rank }}名</h4>
                  <p>当前排名：{{ user_data.rank.rank }}/{{ user_data.user_sum }}</p>
              </li>
          </ul>
      </footer>
  </section>
  <!--follower end-->
  <!--热门题目 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>热门算法题目</h1>
              <p>答题人数最多的题目</p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
{#            {% for item in hot_question %}#}
{#                <tr>#}
{#                  <td>{{ forloop.counter }}</td>#}
{#                  <td>#}
{#                      <a href="{% url 'repo:question_detail' item.id %}" title="{{ item.title }}">{{ item.title }}</a>#}
{#                  </td>#}
{#                  <td>#}
{#                      <span class="label label-info">{{ item.grade }}</span>#}
{#                  </td>#}
{#                </tr>#}
{#            {% endfor %}#}
          {% for item in hot_question %}
                <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>
                      <a href="{% url 'repo:question_detail' item.question__id %}" title="{{ item.question__title }}">{{ item.question__title }}</a>
                  </td>
                  <td>
                      <span class="label label-info">{{ item.question__grade }}</span>
                  </td>
                </tr>
            {% endfor %}
          </tbody>
      </table>
  </section>
  <!--work progress end-->
  <!--近30天刷题用户排行榜 start-->
  <section class="panel">
      <div class="panel-body progress-panel">
          <div class="task-progress">
              <h1>近30天刷题用户排行榜</h1>
              <p></p>
          </div>
      </div>
      <table class="table table-hover personal-task">
          <tbody>
          {% for item in hot_user %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>
                      <a href="javascript:void(0)">{{ item.user__username }}</a>
                  </td>
                  <td>
                      <span>{{ item.id__count }}/{{ user_data.question_all }}</span>
                  </td>
              </tr>
          {% endfor %}
          </tbody>
      </table>
  </section>
  <!--work progress end-->
</aside>
{% endblock %}

question_repo/templates/list.html
{% for contact in contacts.object_list %}
    {# Each "contact" is a Contact model object. #}
    {{ contact }}<br>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if contacts.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ contacts.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
        </span>

        {% if contacts.has_next %}
            <a href="?page={{ contacts.next_page_number }}">next</a>
            <a href="?page={{ contacts.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

question_repo/templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户登录-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
          <form class="form-signin" method="post">
              {% csrf_token %}
            <h2 class="form-signin-heading">登录</h2>
            <div class="login-wrap">
                {{ form.username}}
                {{ form.password}}
                {{ form.captcha}}
                <a href="javascript:void(0);"><img id="captcha_img" src="data:image/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAeCAIAAABoq03CAAACcUlEQVR4nO1aQXLCMAxcMX1A4cwM
    Fz7QQzu8hA8wPKIz/QB/gFM/U9pLf1J+oB4MxrHl2I4dJzDscCAeSZbWliInIWbGBURkXnYAEQHI
    NHKXyGX2gUhMhnYgAJUidwCB6FKxFbFzNwknEH03sflQM0uISE33qNGV8BSUaF//Ua1Tt56n705J
    9XJl+rkOKBVYfktaB7KXkd7nBFktUYgI4IvZUlaTIZcOFWd7TuVvpaB68aQmGozrLmTVzNbMudR2
    HkNpST6wiJHrJqY4mLmDZe1PZY5bXE0mWnS913g6GGfmnm4ewXl9Foodwa3AiGBN9/5uj7jC6o+r
    61NRv/ncHLfQEP74SA6kFPqqtipCy7bvXqSFdV1y1ZvbhAH50tNEYaijmY4ofGAJmmgR0X1V0Bhw
    rsUGoXZ11mvADMuyFrS8qt9mWA7o/1FEi5y2s7xYYLlkRZ2pJNYvZiYSik8KZHf0YGbrEq/uleR0
    xPnNwCuwbyrK96jjkV1HfK4B8o+ZPz+9KoPDezLsvHQXXQbegB+OSOTUgp66O5XK8zNOpzTFgphA
    uFNfbywugha1GPN3sEabKyou7molaqUWFgA9shyzLycwCIVBkw/xjJvY76/UrNcNa+2KX1+uA+cd
    fTgAwN9fVEfY6yPoGDbkProDlU6HoMdBhO32OjKbCerbrWjTNxcAbDYAMJ1eqRex2xVoPPLPvWN5
    xmiV6d9fvLw0RkR5Ey2SzEM+Tjq7MRKibxrucxW3I5RfztZ/95wzo6Vb33m30rrbV3452/c2d7lw
    Z4zn6yaS8lE6gCofWD2IroSxf6nUjhv6jum2ic5Px2pL9Q+TVYba1BF5qAAAAABJRU5ErkJggg==
    " ></a>
                <div class="user-reg">
                    <a href="{% url 'accounts:register' %}"> 用户注册</a>
                    <span class="pull-right"> <a href="{% url 'accounts:passwd_forget' %}"> 忘记密码?</a></span>
                </div>
                <button class="btn btn-lg btn-login btn-block" type="submit">登录</button>
                {{ msg }}
                <p class="msg"></p>
            </div>
          </form>
        </div>
        <script>
            get_captcha_img();
            $("#captcha_img").click(get_captcha_img);

            function get_captcha_img() {
                $.ajax({
                    url: '{% url 'apis:get_captcha' %}',
                    type: 'GET',
                    dataType: 'text',
                    success: function (data) {
                        $('#captcha_img').attr('src', data);
                    }
                });
            }
        </script>
        <script>
            // 这里在form中定义了，如果没定义可以用jquery添加事件
            // $("#id_captcha").blur(check_captcha);

            // 当失去焦点时检查验证码
            function check_captcha() {
                var captcha_code = $('#id_captcha').val();
                if (captcha_code.length == 0){
                    return false
                }
                $.ajax({
                    url: '{% url 'apis:check_captcha' %}',
                    type: 'GET',
                    dataType: 'json',
                    data: {"captcha_code": captcha_code},
                    success: function (data) {
                        if(data.code == 400){
                             $('.msg').html("验证码错误");
                        }else{
                            $('.msg').html("");
                        }
                    }
                });
            };
        </script>
    </body>
</html>

question_repo/templates/passwd_forget.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    请输入绑定的邮箱:<input type="email" placeholder="邮箱" name="email">
    <input type="submit" value="提交">
    {{ msg }}
</form>
</body>
</html>

question_repo/templates/passwd_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    密码1:<input type="password" placeholder="请输入密码" name="password1">
    密码2:<input type="password" placeholder="请再次输入密码" name="password2">
    <input type="submit" value="提交">
    {{ msg }}
</form>
</body>
</html>

question_repo/templates/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="http://127.0.0.1:8000/accounts/login/img/favicon.html">
    <title>用户注册-三创题库系统</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    <script src="{% static 'js/jquery.js' %}"></script>
    {# 加载提示工具对应的js和css #}
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
    <body class="login-body">
        <div class="container">
            <form class="form-signin" id="register_form">
              {% csrf_token %}
              <h2 class="form-signin-heading">用户注册</h2>
              <div class="login-wrap">
                  {{ form.username }}
                  {{ form.password }}
                  {{ form.password2 }}
                  {{ form.mobile }}
                  {{ form.mobile_captcha }}
                  {# 给发送短信按钮添加动作 #}
                  <input onclick="sendmessage(this,60);" type="button" value="发送短信"  class="btn btn-info" style="height:38px;width: 125px;"/>
                  <button class="btn btn-lg btn-login btn-block" type="button" id="register_btn">注册</button>
                  <label class="checkbox">
                      <span class="pull-right"> 已有帐号， <a href="{% url 'accounts:login' %}"> 请登录 </a></span>
                  </label>
                  <div class="alert alert-block alert-danger fade in">
                        <button data-dismiss="alert" class="close close-sm" type="button">
                            <i class="icon-remove"></i>
                        </button>
                        <strong>提醒!</strong> 错误提示信息~~
                  </div>
              </div>
            </form>
        </div>
    {# 添加js动作#}
    <script>
        {# 发送短信验证码 #}
        function sendmessage(obj,second){
            var telRegex = /(13|14|15|17|18)\d{9}/;
            if(telRegex.test($.trim($("#id_mobile").val()))){
                $.ajax({
                    url: "{% url 'apis:mobile_captcha' %}",
                    type: "GET",
                    dataType: "json",
                    data: {"mobile": $("#id_mobile").val()},
                    success: function (data) {
                         $.gritter.add({
                            // (string | mandatory) the heading of the notification
                            title: '提交结果',
                            // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                            text: data.msg
                        });
                    }
                });
                countDown(obj,second)
            } else{
                $.gritter.add({
                    // (string | mandatory) the heading of the notification
                    title: '提交结果',
                    // (string | mandatory) the text inside the notification
                    //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                    text: '手机号有误'
                });
            }
        }

        {# 重新发送倒计时 #}
        function countDown(obj,second){
        // 如果秒数还是大于0，则表示倒计时还没结束
         if(second>=0){
              // 获取默认按钮上的文字
              if(typeof buttonDefaultValue === 'undefined' ){
                buttonDefaultValue =  obj.defaultValue;
            }
            // 按钮置为不可点击状态
            obj.disabled = true;
            // 按钮里的内容呈现倒计时状态
            obj.value = buttonDefaultValue+'('+second+')';
            // 时间减一
            second--;
            // 一秒后重复执行
            setTimeout(function(){countDown(obj,second);},1000);
            // 否则，按钮重置为初始状态
            }else{
            // 按钮置未可点击状态
            obj.disabled = false;
            // 按钮里的内容恢复初始状态
            obj.value = buttonDefaultValue;
           }
        }

    $("#register_btn").click(function () {
          // some_check
          $.ajax({
              url: "{% url 'accounts:register' %}",
              type: "POST",
              dataType: "json",
              data: $("#register_form").serialize(), // {"username":'cali'}
              success: function (data) {
                  if(data.status == 200 ){
                      window.location.href='{% url 'repo:index' %}';
                  }else{
                      msg = "新错误类型";
                      if(data.status == 400 || data.status == 401){
                          msg = data.msg
                      }else{
                          // 402 => form.errors
                          for(var i in data.msg){
                              msg = i+data.msg[i];
                              break
                          }
                      }
                       $.gritter.add({
                          // (string | mandatory) the heading of the notification
                          title: '提交结果',
                          // (string | mandatory) the text inside the notification
                          //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                          text: msg
                      });
                   }
              },
              // 解决csrftoken
              beforeSend: function(xhr, settings) {
                  xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
              }
          });
      });
    </script>

    </body>
</html>

question_repo/templates/uc_answer.html
{% extends 'uc_base.html' %}
{% load staticfiles %}
{% block uc_content %}
  <div class="row">
      <div class="col-lg-12">
          <section class="panel">
              <header class="panel-heading">
                  回答的问题
              </header>
              <table class="table table-striped border-top" id="sample_1">
              <thead>
              <tr>
                  <th style="width:8px;"><input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" /></th>
                  <th class="hidden-phone">问题</th>
                  <th class="hidden-phone">我的答案</th>
                  <th class="hidden-phone">收藏量</th>
              </tr>
              </thead>
              <tbody>
              {% if my_answers %}
              {% for answer in my_answers %}
              <tr class="odd gradeX">
                  <td><input type="checkbox" class="checkboxes" value="1" /></td>
                  <td><a href="{% url 'repo:question_detail' answer.question_id %}">{{ answer.question.title }}</a></td>
                  <td>{{ answer.answer }}</td>
                  <td>{{ answer.answers_collection_set.count }}</td>
              </tr>
              {% endfor %}
              {% else %}<p>你还没有回答问题</p>
              {% endif %}
              </tbody>
              </table>
          </section>
      </div>
  </div>
  <!-- page end-->
{% endblock %}
{% block load_js %}
    <script type="text/javascript" src="{% static 'assets/data-tables/jquery.dataTables.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/data-tables/DT_bootstrap.js '%}"></script>
    <script src="{% static 'js/dynamic-table.js' %}"></script>
{% endblock %}

question_repo/templates/uc_base.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="row">
  <aside class="profile-info col-lg-3">
    <div class="panel">
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
        /* 
        {% url 'uc:profile' as uc_profile %}
        {% url 'uc:change_passwd' as uc_change_passwd %}
        {% url 'uc:answer' as uc_answer %}
        {% url 'uc:collect' as uc_collect %}
        {% url 'uc:contribut' as uc_contribut %}
        {% url 'uc:approval' as uc_approval %}
        */
        <li role="presentation" class="{% if current_url == uc_profile %}active{% endif %}"><a href="{{ uc_profile }}">个人资料</a></li>
        <li role="presentation" class="{% if current_url == uc_change_passwd %}active{% endif %}"><a href="{{ uc_change_passwd }}">修改密码</a></li>
        <li role="presentation" class="{% if current_url == uc_answer %}active{% endif %}"><a href="{{ uc_answer }}">我的回答</a></li>
        <li role="presentation" class="{% if current_url == uc_collect %}active{% endif %}"><a href="{{ uc_collect }}">我的收藏</a></li>
        <li role="presentation" class="{% if current_url == uc_contribut %}active{% endif %}"><a href="{{ uc_contribut }}">我的贡献</a></li>
        {% if perms.repo.can_change_question_status %}
            <li role="presentation" class="{% if current_url == uc_approval %}active{% endif %}"><a href="{{ uc_approval }}">题目审核</a></li>
        {% endif %}
        </ul>
      </div>
    </div>
  </aside>
  <aside class="profile-info col-lg-9">
      <section>
          <div class="row">
            {% block uc_content %}
            {% endblock %}
          </div>
      </section>
  </aside>
</div>

{% endblock %}
{% block load_js %}
  <script src="{% static 'assets/jquery-knob/js/jquery.knob.js' %}"></script>
  <script>
      //knob
      $(".knob").knob();
  </script>
{% endblock %}